version: "3.8"
services:
  postgres:
    container_name: postgres_container
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: job_db
    #    volumes:
    #      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    #      - ./docker/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
    #    networks:
    #      - postgres
    restart: always

  job-portal:
    container_name: job_portal_container
    image: job_portal_img:v1.0
    ports:
      - "8080:8080"
    environment:
      DATASOURCE_URL: jdbc:postgresql://postgres:5433/job_db
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: admin123
    depends_on:
      - postgres
    restart: unless-stopped
