version: "3.8"
services:
  postgres:
    container_name: postgres_container
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: job_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  job-portal:
    container_name: job_portal_container
    image: job_portal_img:v1.1
    ports:
      - "8080:8080"
    environment:
      DATASOURCE_URL: jdbc:postgresql://postgres:5432/job_db
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: admin123
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data: