server:
  servlet:
    context-path: /jobs
spring:
  application:
    name: job-portal

  datasource:
#    url: jdbc:postgresql://localhost:5432/jobs
#    url: jdbc:postgresql://postgres:5432/job_db
#    username: postgres
#    password: admin123
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/job_db}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:admin123}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect